name: Deploy Vue.js App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # - name: Clear cache
      #   run: yarn cache clean

      - name: Install dependencies
        run: yarn install

      - name: Set up environment variables
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL_PRODUCTION }}" > .env.production

      - name: Build project
        run: yarn build --mode production

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST -p $SERVER_PORT "rm -rf /var/www/pengreen.live/*"
          sshpass -p "$SERVER_PASSWORD" rsync -avz -e "ssh -p $SERVER_PORT" --delete dist/ $SERVER_USER@$SERVER_HOST:/var/www/pengreen.live
